# Generated by Django 4.1.12 on 2023-12-07 20:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=5)),
                ('airport_name', models.CharField(max_length=100)),
                ('airport_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('valuable', models.BooleanField(default=False)),
                ('locations', models.CharField(choices=[('DDT', 'Departer Domestic Terminal'), ('DIT', 'Departer International Terminal'), ('SEQ', 'Security Checkpoint'), ('ADT', 'Arrival Domestic Terminal'), ('AIT', 'Arrival International Terminal'), ('CHT', 'Checkin Terminal'), ('FPK', 'Front Parking'), ('BPK', 'Back Parking'), ('air', 'Air Side')], default='DDT', max_length=3)),
                ('model', models.CharField(help_text='BRAND, MODEL, MAKE', max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter phone number', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='found/%Y/%m/%d')),
                ('serial_number', models.CharField(editable=False, max_length=4, unique=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/%Y/%m/%d')),
                ('airport', models.ForeignKey(default='AJF', on_delete=django.db.models.deletion.CASCADE, to='found.airport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_airport', models.ManyToManyField(blank=True, null=True, to='found.airport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('LFI', 'محضر تسليم مضبوطات أو مفقودات')], default='LFI', max_length=3)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='found/%Y/%m/%d')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(choices=[('DDT', 'المغادرة'), ('DIT', 'القدوم'), ('SEQ', 'ضبط'), ('ADT', 'تخلف')], default='DDT', max_length=3)),
                ('item1', models.CharField(blank=True, max_length=100)),
                ('item2', models.CharField(blank=True, max_length=100)),
                ('item3', models.CharField(blank=True, max_length=100)),
                ('item4', models.CharField(blank=True, max_length=100)),
                ('item5', models.CharField(blank=True, max_length=100)),
                ('item6', models.CharField(blank=True, max_length=100)),
                ('item7', models.CharField(blank=True, max_length=100)),
                ('item8', models.CharField(blank=True, max_length=100)),
                ('item9', models.CharField(blank=True, max_length=100)),
                ('item10', models.CharField(blank=True, max_length=100)),
                ('item11', models.CharField(blank=True, max_length=100)),
                ('item12', models.CharField(blank=True, max_length=100)),
                ('item13', models.CharField(blank=True, max_length=100)),
                ('item14', models.CharField(blank=True, max_length=100)),
                ('item15', models.CharField(blank=True, max_length=100)),
                ('item16', models.CharField(blank=True, max_length=100)),
                ('item17', models.CharField(blank=True, max_length=100)),
                ('item18', models.CharField(blank=True, max_length=100)),
                ('item19', models.CharField(blank=True, max_length=100)),
                ('item20', models.CharField(blank=True, max_length=100)),
                ('deliverer', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='found.report')),
            ],
        ),
        migrations.CreateModel(
            name='FoundSubmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('found', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='found.found')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('DEP', 'نقل سجناء'), ('MED-EVAC', 'إخلاء طبي'), ('FUNERAL', 'سيارة نقل الجنائز'), ('OTHER', 'أخرى')], default='DDT', max_length=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='found/%Y/%m/%d')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
